LRDOCS-7841 Code
drewbrokke/liferay-learn pull request #1
Opened 2021-04-08 19:32 UTC by mtokudome

2021-04-09 22:49 UTC, drewbrokke requested changes
Hey @mtokudome, I've left a few comments. It's looking good overall, though I have doubts about the structure of writing our own configuration UI and `MessageDislayConfigurationAction` when System Settings and Instance Settings are designed to provide automatic UIs for configuration interfaces.

What is this article trying to achieve? Is it just to show how to include a configuration class? Or how to use our own portlet preferences in tandem with a configuration interface?

My recommendations will probably change depending on what we're trying to teach the reader with this article.

2021-04-09 22:49 UTC, drewbrokke commented on docs/dxp/7.x/en/developing-applications/core-frameworks/configurable-applications/resources/liferay-c6f7.zip/c6f7-web/src/main/java/com/acme/c6f7/web/internal/configuration/MessageDisplayConfiguration.java
> +
In Configurations throughout portal, an extended attributes annotation is almost always included here in order to define the category. Otherwise this will just get dumped into a generic category that may be unintuitive to find. See https://github.com/liferay/liferay-portal/blob/0e74f1451a6b6231a15cc772f665396c4eae1bae/modules/apps/users-admin/users-admin-api/src/main/java/com/liferay/users/admin/configuration/UserFileUploadsConfiguration.java#L24 for an example.

2021-04-09 22:49 UTC, drewbrokke commented on docs/dxp/7.x/en/developing-applications/core-frameworks/configurable-applications/resources/liferay-c6f7.zip/c6f7-web/build.gradle
> +}
Judging by this `build.gradle`, this module will probably not compile. There are usually quite a few more dependencies needed, so if the goal is to have the user or dev follow along with the example code and end up with a working portlet, we should make sure that the module compiles.

2021-04-09 22:49 UTC, drewbrokke commented on docs/dxp/7.x/en/developing-applications/core-frameworks/configurable-applications/resources/liferay-c6f7.zip/c6f7-web/src/main/resources/META-INF/resources/configuration.jsp
> +if (messageDisplayConfiguration != null) {
Source formatting nitpick: I would declare the `messageDisplayConfiguration` variable after the font variables, separated by a line break. The font variables are of primary importance, with the config variable serving to set their values, so they should be declared first. I'd also order the font variables alphabetically.

PS these are comments I'd leave on a PR that would be committed to liferay-portal. They are not nearly as important for sample code, so take them with a grain of salt :)

2021-04-09 22:49 UTC, drewbrokke commented on docs/dxp/7.x/en/developing-applications/core-frameworks/configurable-applications/resources/liferay-c6f7.zip/c6f7-web/src/main/resources/META-INF/resources/configuration.jsp
> +	/>
The `liferay-portlet` and `aui:input` tags are usually placed all on one line, unless they have a lot of attributes.

2021-04-09 22:49 UTC, drewbrokke commented on docs/dxp/7.x/en/developing-applications/core-frameworks/configurable-applications/resources/liferay-c6f7.zip/c6f7-web/src/main/resources/META-INF/resources/configuration.jsp
> +	</aui:fieldset>
Depending on the goals of this sample code, this could require some changes, or be just fine. If this were a piece of LIferay code, I'd suggest the following changes:

1. For each of the options of each select field, we should be iterating over an array or collection of values and rendering an option tag for each one.
2. The color names displayed in the UI should probably be translated. See `<liferay-ui:message />` in our jsp files for examples.

2021-04-09 22:49 UTC, drewbrokke commented on docs/dxp/7.x/en/developing-applications/core-frameworks/configurable-applications/resources/liferay-c6f7.zip/c6f7-web/src/main/java/com/acme/c6f7/web/internal/configuration/MessageDisplayConfiguration.java
> +	public int fontSize();
Most of the time, configuration fields have a default value (defined by the `default` attribute of the `Meta.AD` annotation. This would make the conditional statement at https://github.com/drewbrokke/liferay-learn/pull/1/files#diff-784004990bbb6b0901e1adf5bf7fdc27557f5b42df1298828e22a3ef8bc532adR35 always false since a config would now always have a value, even if none are saved to the database.

2021-04-09 22:49 UTC, drewbrokke commented on docs/dxp/7.x/en/developing-applications/core-frameworks/configurable-applications/resources/liferay-c6f7.zip/c6f7-web/src/main/java/com/acme/c6f7/web/internal/configuration/MessageDisplayConfiguration.java
> +	public String fontFamily();
It might be a good idea to showcase how configuration fields can have selectable values instead of being a free text field. `fontFamily` might be a good candidate for this since users probably don't think of font family values as easily as something like font colors.

See https://github.com/liferay/liferay-portal/blob/0e74f1451a6b6231a15cc772f665396c4eae1bae/modules/dxp/apps/portal-reports-engine-console/portal-reports-engine-console-web/src/main/java/com/liferay/portal/reports/engine/console/web/internal/admin/configuration/ReportsEngineAdminWebConfiguration.java#L33-L34 for an example.

2021-04-13 18:48 UTC, rbohl commented
@drewbrokke Makoto shared this PR with me--I think I left him in the dark a little bit on how to get the developer articles on HC ported over to Liferay Learn. He's done so much with the User Guide material that I forgot he'd not really understand how different things are when porting our developer material from Help Center/`liferay-docs` to Liferay Learn/`liferay-learn`.

I think he's going to step back, outline the section, and get back to you about providing feedback. Just so you know, In Liferay Learn things are different than they were in Help Center, in these ways:

1. BChan is reviewing our code, so you definitely should be _nitpicky_ about things in the same way you would be for `liferay-portal` :harold-pain:
2. Each article should have a _very_ small compilable code sample, like you can see [here](https://github.com/liferay/liferay-learn/tree/master/docs/dxp/latest/en/liferay-internals/extending-liferay/creating-a-model-listener/resources/liferay-n4g6.zip) for the [Model Listener article](https://learn.liferay.com/dxp/latest/en/liferay-internals/extending-liferay/creating-a-model-listener.html)
3. The `build.gradle` instruction to `compileOnly ... release.portal.api` is legit bro :sunglasses: --[do you even fat jar?](https://liferay.dev/blogs/-/blogs/introducing-the-mega-jar-)
   > I know you don't use the Fat/Mega Jar in the portal itself, I just wanted to say that.

2021-04-21 20:39 UTC, mtokudome commented
Superseded by https://github.com/drewbrokke/liferay-learn/pull/2

2021-04-21 20:39 UTC, closed without merging